### ISSUE TITLE
No such container

### ISSUE THREAD

**Issue by thomasf1** [dtsepelev/meteor-up-letsencrypt#8]
I´ve just setup and deployed a existing project (that worked with mupx) on a new VM. It´s called sorted, but it seems to have trouble to locate the docker containers...

Any idea why it fails on the deploy? (did replace the hostname and some other stuff with "something" after copying it here)

```javascript
[something] - Uploading bundle
[something] - Uploading bundle: SUCCESS
[something] - Sending environment variables
[something] - Sending environment variables: SUCCESS
[something] - Initializing start script
[something] - Initializing start script: SUCCESS
[something] - Invoking deployment process
[something] x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	Error response from daemon: No such container: sorted
	Error response from daemon: No such container: sorted-frontend
	Error response from daemon: No such container: nginx
	Error response from daemon: No such container: nginx-gen
	Error response from daemon: No such container: letsencrypt-companion
	docker: Error response from daemon: Could not get container for sorted.
	See 'docker run --help'.
	-----------------------------------STDOUT-----------------------------------
	base: Pulling from abernix/meteord
	Digest: sha256:5b44a27c1ef8f8453f69d452345a92290e290143e4bb1a6d7819f0bc38b8fd96
	Status: Image is up to date for abernix/meteord:base
	latest: Pulling from meteorhacks/mup-frontend-server
	03e1855d4f31: Already exists
	a3ed95caeb02: Already exists
	a3ed95caeb02: Already exists
	304ae4ee074b: Already exists
	963207107048: Already exists
	d9e2907e9fa4: Already exists
	4abf3e40edd9: Already exists
	3c907a5d5f8f: Already exists
	8db38a632903: Already exists
	Digest: sha256:573a1dd3e0e7829ad16e813d87e79948e9f2ef2cfa84d17c2c4c220b6e651b12
	Status: Image is up to date for meteorhacks/mup-frontend-server:latest
	----------------------------------------------------------------------------
```

Here is my mup.json file (I guess i could remove the ssl section?):
```javascript
{
  // Server authentication info
  "servers": [
    {
      "host": "something",
      "username": "mup",
      "sshOptions": {"port" : 61001},
      "pem": "./ssh-key.pem"
    }
  ],

  "ssl": {
    "certificate": "./fullchain.pem", // this is a bundle of certificates
    "key": "./privkey.pem" // this is the private key of the certificate
    //"backendPort": 80
  },

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": false,

  // Application name (No spaces)
  "appName": "sorted",

  // Lets Encrypt
  "letsEncrypt": {
    "domain": "app.something.com",
    "email": "dev@something.com"
  },

  // Location of app (local directory)
  "app": "../",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "ROOT_URL": "http://app.something.com",
    "MONGO_URL": "mongodb://something",
    "MAIL_URL": "smtp://something",
    "PORT": 80
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 20,

  // show a progress bar while uploading. 
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}
```

**Comment by dtsepelev** [comment]
@thomasf1 yep, you should definitely remove ssl object from mup.json. Which version of meteor do you use?

**Comment by thomasf1** [comment]
Ok, I´ll do... I´m using the latest Meteor afaik (1.4.2.3)...

**Comment by thomasf1** [comment]
Actually, removing the ssl section made it deploy... Really should have tried that earlier...

I guess it would be good to just ignore the SSL part...

**Comment by thomasf1** [comment]
Now that deploying worked I´m getting a 

502 Bad Gateway

on https

and a 

503 Service Temporarily Unavailable

on http...

**Comment by thomasf1** [comment]
Just rebuild the VM, still getting the 503 Service Temporarily Unavailable...

**Comment by thomasf1** [comment]
While the HTTPS gives me a certificate error... ERR_CERT_COMMON_NAME_INVALID

The Name on the certificate is the domain name (subdomain.domain.io)

**Comment by dtsepelev** [comment]
@thomasf1 Do your subdomain is pointing on your instance? Otherwise the ssl certificate could not be generated. To debug the process you can ssh to your instance and try:

`docker logs letsencrypt-companion`
`docker logs nginx`
`docker logs meteor`

**Comment by thomasf1** [comment]
Got it all to work... There where some meteor issues that seemed to popped up with the latest version switch and the version of the mongo database (external)

The advice to look at the logs individually helped, might be good to include that into a troubleshooting section in the readme. Thanks for the advice! :)

PS: "docker logs meteor" is "docker logs <appname>" on my system

**Comment by rnarayan** [comment]
"docker logs meteor" is actually "docker logs $appname". Substitute $appname with the actual name you gave in mup.json file in the key "appName".

If you are unsure about the name, ssh into your server and type the command:
`docker ps`
This will give you a list of all the containers that's running. Pick the names of the containers from the "Names" column in the display table. You should see the following names:

- letsencrypt-companion
- nginx-gen
- nginx
- $appname

You can see their logs by typing the command:
`docker logs &Name` //for example, docker logs nginx

If you want to inspect the files in a container, use the following command to enter the container:
`docker exec -it $Name bash` - You will enter the container terminal and you can use linux commands like ls, cd, cat etc.
For example:
`docker exec -it nginx bash` will enter the nginx container and open its terminal . Once there you can `cd /etc/nginx` to see conf files.

**Comment by dtsepelev** [comment]
@rnarayan yep, thanks for mentioning. I became totally addicted to the default application name after few years of using mupx :)
