### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by lunatolun** [dtsepelev/meteor-up-letsencrypt#9]
I did setup and deploy without problems but the URL gives 502 Bad Gateway. Any ideas?

Ubuntu 14.04.4 x64 - clean installation.

**Comment by dtsepelev** [comment]
@lunatolun which version of meteor and mupx-letsencrypt do you use?

To debug your deployment process you could ssh to your instance and try:
`docker logs letsencrypt-companion`
`docker logs nginx`
`docker logs meteor`

**Comment by lunatolun** [comment]
@dtsepelev , last version of Meteor and whatever version is installed via 'npm install -g mupx-letsencrypt' command.

It is an error with materialize I think. I will check and update.

**Comment by lunatolun** [comment]
@dtsepelev yep, it was because of materialize v.0.98.0
Changing it to 0.97.0 fixed the problem. Cheers
